version: 0.2
env:
  parameter-store:
    REACT_APP_COGNITO_USER_POOL_ID: /dev/web/REACT_APP_COGNITO_USER_POOL_ID
    REACT_APP_COGNITO_CLIENT_ID: /dev/web/REACT_APP_COGNITO_CLIENT_ID
    REACT_APP_COGNITO_DOMAIN: /dev/web/REACT_APP_COGNITO_DOMAIN
    REACT_APP_HOST_DOMAIN: /dev/web/REACT_APP_HOST_DOMAIN
    REACT_APP_COGNITO_REDIRECT_URI: /dev/web/REACT_APP_COGNITO_REDIRECT_URI
  variables:
    REACT_APP_IS_DEV: "prod"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - echo 'Invalidating cache'
      - aws cloudfront create-invalidation --distribution-id E26JM5QIRACOGQ --paths /index.html
artifacts:
  files:
    - "**/*"
  base-directory: "build"
